apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.appid }}
  labels:
    app: {{ .Values.appid }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appid }}
  template:
    metadata:
      labels:
        app: {{ .Values.appid }}
    spec:
      volumes:
        - name: data-volume
          {{- if .Values.localdev }}
          emptyDir: {}
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ .Values.appid }}
          {{- end }}
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: {{ .Values.appid }}
        {{- with .Values.command }}
        command:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.uiport }}
          name: ui-port
        - containerPort: {{ .Values.usageport }}
          name: usage-port
        readinessProbe:
          tcpSocket:
            port: ui-port
          periodSeconds: 5
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
          - mountPath: /opt/trafficparrot-license-usage/data
            name: data-volume
