apiVersion: v2
appVersion: 1.0.0
description: Traffic Parrot License Server Helm Chart for Kubernetes, exposed through an Ingress controller
name: traffic-parrot-license-server
type: application
version: 2.0.0
